#include 'define.h'
    
    SUBROUTINE ALLOCATION
    
#ifdef PRE_HYD        
        USE HYDRO
#endif

#ifdef PRE_AD
        USE Morphodynamics
#endif

#ifdef PRE_BANK_EROSION
        USE BANK_EROSION
        USE EXCHANGE
        USE SED_EXCHANGE
        USE DEF_EXCHANGE
#endif

#ifdef PRE_BANK_COLLAPSE
        USE BANK_COLLAPSE
#endif        

        IMPLICIT NONE
        INTEGER:: I,J
        
#ifdef PRE_HYD 
        ! HYDRO ARRAIES READY
        ALLOCATE(P1(M_START : M_END,N_START : N_END))
        ALLOCATE(P2(M_START : M_END,N_START : N_END))
        ALLOCATE(Q1(M_START : M_END,N_START : N_END))
        ALLOCATE(Q2(M_START : M_END,N_START : N_END))
        ALLOCATE(H1(M_START : M_END,N_START : N_END))
        ALLOCATE(H2(M_START : M_END,N_START : N_END))
    
        ! DEPTH ARRAIES READY
        ALLOCATE(DEP(M_START : M_END,N_START  : N_END))
        ALLOCATE(NDD(M_START : M_END,N_START  : N_END))
        ALLOCATE(VDDX(M_START : M_END,N_START : N_END))
        ALLOCATE(VDDY(M_START : M_END,N_START : N_END))
        ALLOCATE(IDN(2,              M_START  : M_END))
        ALLOCATE(JDN(2,              N_START  : N_END)) 

        ! H_PARAMETERS READY
        ALLOCATE(DX1(M_START : M_END,N_START : N_END))
        ALLOCATE(DY1(M_START : M_END,N_START : N_END))  

        ! Q~A RELATIONSHIP
        ALLOCATE(QA_Q (30,N_END))
        ALLOCATE(QA_A (30,N_END))        
        ALLOCATE(QA_Q_P (30,3,N_END))
        ALLOCATE(QA_A_P (30,3,N_END)) 
        
        ! BANK
        ALLOCATE(BANK_H(NUMBER_BV))
#endif
 
#ifdef PRE_AD
        ! Morphodynamics ARRAIES READY
        ALLOCATE(C1(M_START : M_END,N_START  : N_END))
        ALLOCATE(C2(M_START : M_END,N_START  : N_END))
#endif
        
#ifdef PRE_BANK_EROSION
        ! BANK_EROSION READY
        ALLOCATE(POSITION(NUMBER_BV,NUMBER_OB))
        ALLOCATE(BVP(NUMBER_BV,2))
        ALLOCATE(BVP_IN(NUMBER_BV,2))
        ALLOCATE(BVP_JUDGE(NUMBER_BV))       
        ALLOCATE(BVP_VELOCITY(12,NUMBER_BV))
        ALLOCATE(QE_OUT(NUMBER_BV*3,1000)) !第1行QE_BANK, 第2行QE_BED, 第3行QE_CREEK
        
        !JUDGE_BANK READY
        ALLOCATE(JUDGE_BANK (NUMBER_BV))
        ALLOCATE(JUDGE_TIME (NUMBER_BV))
        ALLOCATE(BF (NUMBER_BV,4))
        ALLOCATE(NUMBER_LOAD(NUMBER_BV))
        ALLOCATE(NUMBER_BANKCYCLE(NUMBER_BV))
        ALLOCATE(LENGTH_COLLAPSE_BEFORE(NUMBER_BV)) 
        !ALLOCATE(LENGTH_COLLAPSE(NUMBER_BV,1000)) !默认坍塌在1000次内,后面可能需改正
        !ALLOCATE(LENGTH_FLOW(NUMBER_BV,1000))
        !ALLOCATE(LENGTH_RETREATS(NUMBER_BV,1000))
        !ALLOCATE(RETREATS_TOTAL(NUMBER_BV)) 
        ALLOCATE(UPDATE_C(NUMBER_BV)) 
        ALLOCATE(LENGTH_EROSION_DAY(NUMBER_BV))
        ALLOCATE(LENGTH_COLLAPSE_DAY(NUMBER_BV))
        
        !JUDGE_BANK READY
        ALLOCATE(LHL(NUMBER_BV))
        ALLOCATE(LHLB(NUMBER_BV))
        ALLOCATE(STATION_BANK(NUMBER_BV))
        ALLOCATE(ZOOMIN(NUMBER_BV))
        
        !SED_EXCHANGE READY
        ALLOCATE(S_BANK_EROSION(NUMBER_BV)) 
        ALLOCATE(S_BANK_COLLAPSE(NUMBER_BV))
        
        !READ NUMBER OF MESH/NODE
        OPEN (UNIT=40 , FILE='初始网格节点个数、单元个数.TXT' ,STATUS='OLD')
        READ (40,*) EXCHANGE1%NODE, EXCHANGE1%ELEMENT
        CLOSE(40)
        
        !EXCHANGE PARAMETER READY
        ALLOCATE(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_BV,EXCHANGE1%ELEMENT,11))
        ALLOCATE(EXCHANGE1%ZOOMIN(NUMBER_BV))
        ALLOCATE(EXCHANGE1%GRID(EXCHANGE1%NODE,2))
        ALLOCATE(EXCHANGE1%MESH(EXCHANGE1%ELEMENT,3))
        ALLOCATE(EXCHANGE1%DIG_NUMBER(NUMBER_BV,EXCHANGE1%NODE))
        ALLOCATE(EXCHANGE1%JUDGE_BANK(NUMBER_BV))
        ALLOCATE(EXCHANGE1%FLOWEROSION_CHECK(NUMBER_BV))
        ALLOCATE(EXCHANGE1%NUMBER_LOAD(NUMBER_BV))
        ALLOCATE(EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_BV))
        ALLOCATE(EXCHANGE1%FLOW_EXCESS_JUDGE(NUMBER_BV))
        ALLOCATE(EXCHANGE1%COLLAPSE_TIME(NUMBER_BV,1000))
        ALLOCATE(EXCHANGE1%COLLAPSE_DEF(NUMBER_BV,1000))
        ALLOCATE(EXCHANGE1%COLLAPSE_VOLUME(NUMBER_BV,1000))
        ALLOCATE(EXCHANGE1%FLOWEROSION_VOLUME(NUMBER_BV,1000))
        ALLOCATE(EXCHANGE1%SHIELD_VOLUME(NUMBER_BV,1000))
        ALLOCATE(EXCHANGE1%BANKEROSION_VOLUME(NUMBER_BV,3))
#endif

#ifdef PRE_BANK_COLLAPSE
        ALLOCATE( BANKCOLLAPSE%MODULUS(NUMBER_BV,EXCHANGE1%ELEMENT) )
        ALLOCATE( BANKCOLLAPSE%TSTRESS(NUMBER_BV,EXCHANGE1%ELEMENT,7) )
        ALLOCATE( BANKCOLLAPSE%STATION(NUMBER_BV,EXCHANGE1%ELEMENT) )
        ALLOCATE( BANKCOLLAPSE%F(NUMBER_BV,2*EXCHANGE1%NODE) )
        ALLOCATE( BANKCOLLAPSE%WY(NUMBER_BV,2*EXCHANGE1%NODE) )
        ALLOCATE( BANKCOLLAPSE%RESTRICTION(2*EXCHANGE1%NODE) )
        ALLOCATE( BANKCOLLAPSE%MATCH(EXCHANGE1%NODE,10) )
#endif

    END SUBROUTINE ALLOCATION