#include 'define.h'   
#ifdef PRE_BANK_COLLAPSE
SUBROUTINE BANK_UPDATA(NUMBER_I)
            
#ifdef PRE_HYD        
    USE HYDRO
#endif

#ifdef PRE_AD
    USE Morphodynamics
#endif

#ifdef PRE_BANK_EROSION
    USE BANK_EROSION
    USE DEF_EXCHANGE
    USE SED_EXCHANGE
#endif

#ifdef PRE_BANK_COLLAPSE
    USE BANK_COLLAPSE
#endif 

    IMPLICIT NONE
    
    INTEGER :: I, J, P, K, NUMBER_I
    REAL*8  :: TEMP, X1, X2, X3, Y1, Y2, Y3
    
    ! ZOOMIN RESET
    EXCHANGE1%ZOOMIN(NUMBER_I) = BANK_H(NUMBER_I)/EXCHANGE1%GRID_BANK_H
    !EXCHANGE1%ZOOMIN(P       ) = BANK_H(P       )/EXCHANGE1%GRID_BANK_H
        
    ! BANK SIZE RESET
    EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,:,:)=0.D0  
    DO J = 1 , EXCHANGE1%ELEMENT
        X1=EXCHANGE1%ZOOMIN(NUMBER_I)*EXCHANGE1%GRID(EXCHANGE1%MESH(J,1),1) 
        X2=EXCHANGE1%ZOOMIN(NUMBER_I)*EXCHANGE1%GRID(EXCHANGE1%MESH(J,2),1) 
        X3=EXCHANGE1%ZOOMIN(NUMBER_I)*EXCHANGE1%GRID(EXCHANGE1%MESH(J,3),1) 
        Y1=EXCHANGE1%ZOOMIN(NUMBER_I)*EXCHANGE1%GRID(EXCHANGE1%MESH(J,1),2) 
        Y2=EXCHANGE1%ZOOMIN(NUMBER_I)*EXCHANGE1%GRID(EXCHANGE1%MESH(J,2),2) 
        Y3=EXCHANGE1%ZOOMIN(NUMBER_I)*EXCHANGE1%GRID(EXCHANGE1%MESH(J,3),2)
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,10)=0.5D0*ABS(Y3*(X2-X1)+Y1*(X3-X2)+Y2*(X1-X3))
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,1)=EXCHANGE1%MESH(J,1) 
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,2)=EXCHANGE1%MESH(J,2) 
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,3)=EXCHANGE1%MESH(J,3)
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,4)=X1 
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,5)=Y1
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,6)=X2
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,7)=Y2
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,8)=X3 
        EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,J,9)=Y3
    END DO 
        
    ! BANK RECORDER RESET
    POSITION(NUMBER_I,:) = EXCHANGE1%GRID_BANK_W*EXCHANGE1%ZOOMIN(NUMBER_I)
    !POSITION(P       ,:) = EXCHANGE1%GRID_BANK_W*EXCHANGE1%ZOOMIN(P       )
        
    ! DIG NUMBER RESET
    EXCHANGE1%DIG_NUMBER(NUMBER_I,:) = 0
        
    ! BANK STRESS/WY RESET
    BANKCOLLAPSE%WY(NUMBER_I,:) = 0.D0
    BANKCOLLAPSE%TSTRESS(NUMBER_I,:,:) = 0.D0
    BANKCOLLAPSE%STATION(NUMBER_I,:) = 0
        
    ! SOIL PARAMETER RESET
    BANKCOLLAPSE%MODULUS(NUMBER_I,:) = BANKCOLLAPSE%MODULUS_INITIAL
        
    ! BANK LOADCYCLE RESET
    EXCHANGE1%NUMBER_LOAD(NUMBER_I) = 0
    !EXCHANGE1%NUMBER_LOAD(P       ) = 0
        
    ! BANK STATE RESET
    EXCHANGE1%JUDGE_BANK(NUMBER_I) = 0
    !EXCHANGE1%JUDGE_BANK(P       ) = 0
    EXCHANGE1%FLOW_EXCESS_JUDGE(NUMBER_I) = 0
    !EXCHANGE1%FLOW_EXCESS_JUDGE(P       ) = 0
        
    ! NUMBER OF BANKCYCLE +1
    EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I) = EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I)+1    
        
    ! NEW BANK, SIMULATE BANK STRESS FIELD  
    CALL INITIAL_BANK_STRESS(NUMBER_I)
        
    ! OUTPUT ZOOMIN
    CALL OUTPUT_ZOOMIN(NUMBER_I)
 
    
    END SUBROUTINE
#endif
    