#include 'define.h'
#ifdef PRE_BANK_COLLAPSE    
SUBROUTINE BANK_EXTERNAL_FORCE(NUMBER_I, NUMBER_J)
#ifdef PRE_HYD        
        USE HYDRO
#endif

#ifdef PRE_AD
        USE Morphodynamics
#endif

#ifdef PRE_BANK_EROSION
        USE BANK_EROSION
        USE DEF_EXCHANGE
#endif

#ifdef PRE_BANK_COLLAPSE
        USE BANK_COLLAPSE
#endif 
        
        IMPLICIT NONE
        INTEGER , PARAMETER                        :: LEE=SELECTED_REAL_KIND(8)
        REAL(LEE) , ALLOCATABLE , DIMENSION(:,:)   :: B , BT , GRID
        INTEGER   , ALLOCATABLE , DIMENSION(:)     :: DIG_NODE !开挖面上的节点
        INTEGER                                    :: I , J , K , DIG_NUMBER , NUMBER_I , NUMBER_J
        LOGICAL                                    :: TEMP1 , TEMP2
        REAL(LEE)                                  :: TEMP
        CHARACTER*40                               :: FILENAME , FILENAME1 , FILENAME_PATH

        ALLOCATE( B (3,6) )
        ALLOCATE( BT(6,3) )
		ALLOCATE( DIG_NODE(1000) )
                
        BANKCOLLAPSE%F(NUMBER_I,:) = 0.D0
        
        !加开挖荷载, 单位为KN
        DO I = 1, EXCHANGE1%ELEMENT        
        
            IF ( EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, I, 11) .NE. 1.D0 ) CYCLE
            
            B =0.D0
            BT=0.D0     
            B(1,1)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,7)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,9)     
            B(1,3)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,9)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,5)     
            B(1,5)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,5)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,7)
            B(2,2)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,8)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,6)     
            B(2,4)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,4)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,8)     
            B(2,6)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,6)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,4)
            B(3,1)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,8)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,6)     
            B(3,2)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,7)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,9)     
            B(3,3)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,4)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,8)
            B(3,4)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,9)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,5)     
            B(3,5)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,6)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,4)     
            B(3,6)=EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,5)-EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,7)
            BT=TRANSPOSE(B)

            BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,1))-1)  = &
		 &	BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,1))-1)  + &
		 &          0.5D0*BANKCOLLAPSE%T_LE*( BT(1,1)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 1) + &
		 &                                    BT(1,2)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 2) + &
		 &                                    BT(1,3)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 3) ) 
			               
            BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,1))  )  = &
         &  BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,1))  )  + &
		 &		   0.5D0*BANKCOLLAPSE%T_LE*( BT(2,1)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 1)  + &
	     &	  				                 BT(2,2)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 2)  + &
         &									 BT(2,3)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 3)  ) 
            
            BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,2))-1)  = &
		 &  BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,2))-1)  + &
		 &		   0.5D0*BANKCOLLAPSE%T_LE*( BT(3,1)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 1)  + &
		 &									 BT(3,2)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 2)  + &
		 &									 BT(3,3)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 3) )
         
            BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,2))  )  = &
         &	BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,2))  )  + &
		 &	       0.5D0*BANKCOLLAPSE%T_LE*( BT(4,1)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 1)  + &
		 &								     BT(4,2)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 2)  + &
		 &								     BT(4,3)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 3) )        

            BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,3))-1)  = &
		 &  BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,3))-1)  + &
		 &		   0.5D0*BANKCOLLAPSE%T_LE*( BT(5,1)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 1)  + &
	     &									 BT(5,2)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 2)  + &
         &									 BT(5,3)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 3) ) 
         
            BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,3))  )  = &
		 &  BANKCOLLAPSE%F(NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,3))  )  + &
		 &		   0.5D0*BANKCOLLAPSE%T_LE*( BT(6,1)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 1)  + &
		 &									 BT(6,2)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 2)  + &
		 &									 BT(6,3)*BANKCOLLAPSE%TSTRESS(NUMBER_I, I, 3) )

            !需加土荷载
            BANKCOLLAPSE%F( NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,1)) ) = &
         &	BANKCOLLAPSE%F( NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,1))	) - &
         &  EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,10)*(SANDDENSITY_BANK-1000)*10/3.D0/1000.D0*BANKCOLLAPSE%T_LE  
         
            BANKCOLLAPSE%F( NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,2)) ) = &
         &	BANKCOLLAPSE%F( NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,2))	) - &
         &	EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,10)*(SANDDENSITY_BANK-1000)*10/3.D0/1000.D0*BANKCOLLAPSE%T_LE  
         
            BANKCOLLAPSE%F( NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,3)) ) = &
         &	BANKCOLLAPSE%F( NUMBER_I, 2*INT(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,3))	) - &
         &	EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,10)*(SANDDENSITY_BANK-1000)*10/3.D0/1000.D0*BANKCOLLAPSE%T_LE  
         
        END DO
        
        !FILENAME=''
        !WRITE(FILENAME(1:4),'(I4.4)') NUMBER_I
        !FILENAME(5:9)='F.RES'
        !FILENAME_PATH='MATLAB_PLOT\'//FILENAME
        !OPEN (UNIT=100 , FILE=FILENAME_PATH , FORM='UNFORMATTED' , STATUS='REPLACE' , ACCESS='DIRECT' , RECL=2*2)
        !DO I = 1 , EXCHANGE1%NODE
        !    WRITE(100 , REC=I )BANKCOLLAPSE%F(NUMBER_I,2*I-1),BANKCOLLAPSE%F(NUMBER_I,2*I)
        !END DO
        !CLOSE(100)   
        !!WRITE(*,*)1 
        !PAUSE   
        
        
        
        DIG_NODE  =0
        DIG_NUMBER=0
        ! 找出开挖面上的节点 
LOOP1:  DO I = 1, EXCHANGE1%NODE
            TEMP1=.FALSE. !未开挖
            TEMP2=.FALSE. !刚开挖
LOOP2:      DO J = 1 , 10
                IF ( BANKCOLLAPSE%MATCH(I,J)==0 ) CYCLE
                IF ( EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 11)==0.D0) TEMP1=.TRUE.
                IF ( EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 11)==1.D0) TEMP2=.TRUE.
                IF (TEMP1 .AND. TEMP2) THEN
                   DIG_NUMBER=DIG_NUMBER+1 
                   DIG_NODE(DIG_NUMBER)=I
                   EXIT LOOP2
                END IF
            END DO LOOP2
        END DO LOOP1

        !WRITE(*,*)DIG_NUMBER
        !DO I = 1 , DIG_NUMBER
        !    WRITE(*,*)BANKCOLLAPSE%F(NUMBER_I, 2*DIG_NODE(I)-1),BANKCOLLAPSE%F(NUMBER_I, 2*DIG_NODE(I))
        !END DO
        !PAUSE

        !只施加开挖面上的荷载
        DO I = 1, EXCHANGE1%NODE  
            K=0
            DO J = 1, DIG_NUMBER
                IF (DIG_NODE(J)==I) K=1
            END DO
            IF (K==0) BANKCOLLAPSE%F(NUMBER_I, 2*I-1)=0.D0
            IF (K==0) BANKCOLLAPSE%F(NUMBER_I, 2*I  )=0.D0  
        END DO  

               
        
        !FILENAME=''
        !WRITE(FILENAME(1:4),'(I4.4)') NUMBER_I
        !FILENAME(5:9)='F.RES'
        !FILENAME_PATH='MATLAB_PLOT\'//FILENAME
        !OPEN (UNIT=100 , FILE=FILENAME_PATH , FORM='UNFORMATTED' , STATUS='REPLACE' , ACCESS='DIRECT' , RECL=2*2)
        !DO I = 1 , EXCHANGE1%NODE
        !    WRITE(100 , REC=I )BANKCOLLAPSE%F(NUMBER_I,2*I-1),BANKCOLLAPSE%F(NUMBER_I,2*I)
        !END DO
        !CLOSE(100)   
        !PAUSE 

        TEMP=0.D0
        DO I = 1 , DIG_NUMBER
            IF ( DABS(BANKCOLLAPSE%F(NUMBER_I, 2*DIG_NODE(I)-1)) > DABS(TEMP) ) TEMP=BANKCOLLAPSE%F(NUMBER_I, 2*DIG_NODE(I)-1)
            IF ( DABS(BANKCOLLAPSE%F(NUMBER_I, 2*DIG_NODE(I)  )) > DABS(TEMP) ) TEMP=BANKCOLLAPSE%F(NUMBER_I, 2*DIG_NODE(I)  )
        END DO
        
        
        !WRITE(*,*)DIG_NUMBER,TEMP
        !PAUSE
        
        
        !荷载分多少份加载
        NUMBER_J=CEILING(ABS(TEMP)/0.5) 
        
        !WRITE(*,*)NUMBER_J
        !PAUSE
        
        ! 无开挖不计算应力变化
        IF (TEMP==0) NUMBER_J=0 
!        WRITE(*,*)NUMBER_J
!        PAUSE
!        NUMBER_J=1
        !施加的最大荷载小于2kN
        BANKCOLLAPSE%F(NUMBER_I,:) = BANKCOLLAPSE%F(NUMBER_I,:)/NUMBER_J
!        WRITE(*,*)NUMBER_I
!        DO I=1,DIG_NUMBER
!            WRITE(*,*)F(DIG_NODE(I))
!        END DO
!        PAUSE
!        DO I = 1,2*NODE
!        IF (F(I)==0.D0)CYCLE
!        WRITE(*,*)F(I)
!        END DO
!        WRITE(*,*)NUMBER_J 
!        PAUSE
        
        
        IF ( ALLOCATED( B ) ) DEALLOCATE( B )
        IF ( ALLOCATED( BT ) ) DEALLOCATE( BT )      
        IF ( ALLOCATED( DIG_NODE ) ) DEALLOCATE( DIG_NODE )

        RETURN
    END SUBROUTINE BANK_EXTERNAL_FORCE
#endif     