#include 'define.h'   
#ifdef PRE_BANK_COLLAPSE
SUBROUTINE COLLAPSE_EXCHANGES(NUMBER_I)
            
#ifdef PRE_HYD        
    USE HYDRO
#endif

#ifdef PRE_AD
    USE Morphodynamics
#endif

#ifdef PRE_BANK_EROSION
    USE BANK_EROSION
    USE DEF_EXCHANGE
    USE SED_EXCHANGE
#endif

#ifdef PRE_BANK_COLLAPSE
    USE BANK_COLLAPSE
#endif 

    IMPLICIT NONE
    
    INTEGER :: I, J, K, NUMBER_I
    REAL*8  :: TEMP, X1, X2, X3, Y1, Y2, Y3
    
    IF ( EXCHANGE1%JUDGE_BANK(NUMBER_I) == 1 .OR. EXCHANGE1%FLOW_EXCESS_JUDGE(NUMBER_I) == 1) THEN
        !WRITE(*,*) 4
        EXCHANGE1%FLOW_EXCESS_JUDGE(NUMBER_I) = 0
        
        ! CALCULATE VOLUME OF BANK COLLAPSE 需要考虑flow erosion导致的岸壁高度减小，因而坍塌体积会有变化！！！！未来修改
        IF ( EXCHANGE1%COLLAPSE_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I)) ==0.D0 ) THEN
            S_BANK_COLLAPSE(NUMBER_I)=0.D0
            !WRITE(*,*) 1
        ELSE
            S_BANK_COLLAPSE(NUMBER_I) = EXCHANGE1%COLLAPSE_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I))*BANK_H(NUMBER_I)*DX1(1,1) - &
        &                               EXCHANGE1%FLOWEROSION_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I))
            !WRITE(*,*) 2, BANK_H(NUMBER_I), S_BANK_COLLAPSE(NUMBER_I), EXCHANGE1%FLOWEROSION_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I))
        END IF
        
        EXCHANGE1%COLLAPSE_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I))=S_BANK_COLLAPSE(NUMBER_I)
        EXCHANGE1%BANKEROSION_VOLUME(NUMBER_I, 2) = EXCHANGE1%BANKEROSION_VOLUME(NUMBER_I, 2) + EXCHANGE1%COLLAPSE_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I))
        
        ! BED LEVEL CHANGES INDUCED BY BANK COLLAPSE
        TEMP = S_BANK_COLLAPSE(NUMBER_I)/DX1(1,1)/DY1(1,1)     

        DO K = 1 , 5
            IF ( NUMBER_I<=NUMBER_BV/2 ) THEN
                ! DECREASE IN BANK ELEVATION
                DEP( BVP(NUMBER_I,1)-1, BVP(NUMBER_I,2)-3+K )=DEP( BVP(NUMBER_I,1)-1, BVP(NUMBER_I,2)-3+K )+TEMP     
                ! INCREASE IN CREEK BOTTOM
                DEP( BVP(NUMBER_I,1), BVP(NUMBER_I,2)-3+K )=DEP( BVP(NUMBER_I,1), BVP(NUMBER_I,2)-3+K )-TEMP*BANKCOLLAPSE%COLL_TO_BED 
            ELSE
                ! DECREASE IN BANK ELEVATION
                DEP( BVP(NUMBER_I,1)+1, BVP(NUMBER_I,2)-3+K )=DEP( BVP(NUMBER_I,1)+1, BVP(NUMBER_I,2)-3+K )+TEMP     
                ! INCREASE IN CREEK BOTTOM
                DEP( BVP(NUMBER_I,1), BVP(NUMBER_I,2)-3+K )=DEP( BVP(NUMBER_I,1), BVP(NUMBER_I,2)-3+K )-TEMP*BANKCOLLAPSE%COLL_TO_BED 
            END IF                     
        END DO
        
        ! INCREASE IN SSC DUE TO COLLAPSE
        S_BANK_COLLAPSE(NUMBER_I) = S_BANK_COLLAPSE(NUMBER_I)*(1-BANKCOLLAPSE%COLL_TO_BED)
        
        ! CHANGE BANK HEIGHT
        IF ( NUMBER_I<=NUMBER_BV/2 ) THEN
            BANK_H(NUMBER_I)=-DEP( BVP(NUMBER_I,1)-1, BVP(NUMBER_I,2) )+DEP( BVP(NUMBER_I,1), BVP(NUMBER_I,2) )
        ELSE
            BANK_H(NUMBER_I)=-DEP( BVP(NUMBER_I,1)+1, BVP(NUMBER_I,2) )+DEP( BVP(NUMBER_I,1), BVP(NUMBER_I,2) )
        END IF
        
        ! CHANGE POSITION OF BVP
        IF ( BANK_H(NUMBER_I)<=BANK_EROSION_LIMIT ) THEN 
            IF ( NUMBER_I<=NUMBER_BV/2 ) THEN
                BVP(NUMBER_I,1)=BVP(NUMBER_I,1)-1
                BANK_H(NUMBER_I)=-DEP( BVP(NUMBER_I,1)-1, BVP(NUMBER_I,2) )+DEP( BVP(NUMBER_I,1), BVP(NUMBER_I,2) ) 
            ELSE
                BVP(NUMBER_I,1)=BVP(NUMBER_I,1)+1
                BANK_H(NUMBER_I)=-DEP( BVP(NUMBER_I,1)+1, BVP(NUMBER_I,2) )+DEP( BVP(NUMBER_I,1), BVP(NUMBER_I,2) )
            END IF
            
            IF ( BANK_H(NUMBER_I)<=BANK_EROSION_LIMIT ) EXCHANGE1%FLOWEROSION_CHECK(NUMBER_I)=1
        END IF 
        
        ! BANK UPDATA
        CALL BANK_UPDATA(NUMBER_I)

        
    END IF

    
END SUBROUTINE COLLAPSE_EXCHANGES  
#endif    
    


