#include 'define.h'
#ifdef PRE_BANK_COLLAPSE     
SUBROUTINE FAILURE_CRITERION(NUMBER_I)
    USE TIME_DIN
#ifdef PRE_BANK_EROSION
    USE BANK_EROSION
    USE DEF_EXCHANGE
#endif

#ifdef PRE_BANK_COLLAPSE
    USE BANK_COLLAPSE
#endif
    
    IMPLICIT NONE
    
    INTEGER  , PARAMETER                       :: FC=SELECTED_REAL_KIND(8)
    REAL(FC)                                   :: TEMP , TEN_C , A
    INTEGER                                    :: I , J , K , NUMBER_I , NUMBER_J
    CHARACTER*40                               :: FILENAME1 , FILENAME_PATH


    TEMP = 180.D0/3.1415926*0.5D0
    DO I = 1 , EXCHANGE1%ELEMENT
        BANKCOLLAPSE%TSTRESS(NUMBER_I,I,4) = 0.5D0*(BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1)+BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)) +  &
        &                            DSQRT( 0.25D0*(BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2))**2 + BANKCOLLAPSE%TSTRESS(NUMBER_I,I,3)**2 )
        
        BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5) = 0.5D0*(BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1)+BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)) -  &
        &                            DSQRT( 0.25D0*(BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2))**2 + BANKCOLLAPSE%TSTRESS(NUMBER_I,I,3)**2 )
       !角度方向规定：以x轴为始边，顺时针为负
        BANKCOLLAPSE%TSTRESS(NUMBER_I,I,6) = 90.D0 + TEMP*ATAND( -2.D0*BANKCOLLAPSE%TSTRESS(NUMBER_I,I,3)/(BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)) )  
    END DO

    !土力学中以压力为正；拉力为负，与弹性力学相反
    BANKCOLLAPSE%TSTRESS(NUMBER_I,:,4) = -BANKCOLLAPSE%TSTRESS(NUMBER_I,:,4)
    BANKCOLLAPSE%TSTRESS(NUMBER_I,:,5) = -BANKCOLLAPSE%TSTRESS(NUMBER_I,:,5)
    
    !找出大、小主应力
    DO I = 1 , EXCHANGE1%ELEMENT        
        IF (BANKCOLLAPSE%TSTRESS(NUMBER_I,I,4)<BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5)) THEN
            TEMP        = BANKCOLLAPSE%TSTRESS(NUMBER_I,I,4)
            BANKCOLLAPSE%TSTRESS(NUMBER_I,I,4) = BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5)
            BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5) = TEMP
        END IF
    END DO

    !破坏判断--拉破坏判断
    !TEN_C=-BANKCOLLAPSE%COH*DTAND(BANKCOLLAPSE%FRI)
    TEN_C=-BANKCOLLAPSE%COH/DTAND(BANKCOLLAPSE%FRI)*0.3
    !write(*,*)ten_c
    !pause
    TEN_C=-2.5D0
!     TEN_C=-COH*0.5D0
!    TEN_C=-7.D0
!    ALLOCATE( STATION (ELEMENT) )
!    STATION =0 !0稳定、1拉破话、2剪破坏
    DO I = 1 , EXCHANGE1%ELEMENT
        IF ( BANKCOLLAPSE%STATION( NUMBER_I, I ) == 1 .OR. BANKCOLLAPSE%STATION( NUMBER_I, I ) == 2 ) CYCLE
        !拉破坏判断假设竖向应力不变
        IF (BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5) <= TEN_C) THEN  
            BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5)=0.1D0
            TEMP=BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1)
            A=( BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1) )/ & 
        &     ( BANKCOLLAPSE%TSTRESS(NUMBER_I,I,4)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5) )
            BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1)=( 1.D0-2.D0*A/(1.D0+A) )*BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)
            BANKCOLLAPSE%TSTRESS(NUMBER_I,I,3)=BANKCOLLAPSE%TSTRESS(NUMBER_I,I,3)*( BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1) )/( BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)-TEMP )
            !剪破坏也进行拉破坏修正，若同时破坏，显示为剪破坏
            IF (BANKCOLLAPSE%STATION( NUMBER_I, I ) .NE. 2) BANKCOLLAPSE%STATION( NUMBER_I, I )=1 
            !待修改??弹性模量设为极小值
            BANKCOLLAPSE%MODULUS(NUMBER_I, I) = 0.1D0*BANKCOLLAPSE%MODULUS_INITIAL  
        END IF
    END DO
    
    !破坏判断--剪破坏判断
    DO I = 1 , EXCHANGE1%ELEMENT
        IF (BANKCOLLAPSE%STATION( NUMBER_I, I ) == 2 .OR. BANKCOLLAPSE%STATION( NUMBER_I, I ) == 1) CYCLE
        TEMP=BANKCOLLAPSE%TSTRESS(NUMBER_I,I,4)*DTAND(45.D0-0.5D0*BANKCOLLAPSE%FRI)**2-2.D0*BANKCOLLAPSE%COH*DTAND(45.D0-0.5D0*BANKCOLLAPSE%FRI)
        !剪破坏判断假设竖向应力不变
        IF (TEMP > BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5)) THEN    
           A=2.D0*( BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)*DSIND(BANKCOLLAPSE%FRI)+BANKCOLLAPSE%COH*DCOSD(BANKCOLLAPSE%FRI) )/( (BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1))*DSIND(BANKCOLLAPSE%FRI)+BANKCOLLAPSE%TSTRESS(NUMBER_I,I,4)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,5) )
           BANKCOLLAPSE%TSTRESS(NUMBER_I,I,3)=A*BANKCOLLAPSE%TSTRESS(NUMBER_I,I,3)
           BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1)=BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)-A*(BANKCOLLAPSE%TSTRESS(NUMBER_I,I,2)-BANKCOLLAPSE%TSTRESS(NUMBER_I,I,1))
           IF (BANKCOLLAPSE%STATION( NUMBER_I, I ) .NE. 1) BANKCOLLAPSE%STATION( NUMBER_I, I ) = 2
           !待修改??弹性模量设为极小值
           BANKCOLLAPSE%MODULUS(NUMBER_I, I)=0.1D0*BANKCOLLAPSE%MODULUS_INITIAL   
        END IF
    END DO

    ! 判断是否更换新岸壁
    EXCHANGE1%JUDGE_BANK(NUMBER_I) = 1
LOOP1:DO I = 2, NUMBER_OB-2
        TEMP=EXCHANGE1%ZOOMIN(NUMBER_I)*EXCHANGE1%GRID_BANK_H/(NUMBER_OB-1)*I
        K=0
LOOP2:  DO J = 1, EXCHANGE1%ELEMENT
            ! 避免挖去单元影响
            IF ( EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, J, 11) == 1.D0) CYCLE
            
            IF ( EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, J, 5) > TEMP .AND.  &
            &    EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, J, 7) > TEMP .AND.  &
            &    EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, J, 9) > TEMP ) CYCLE
            
            IF ( EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, J, 5) < TEMP .AND.  &
            &    EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, J, 7) < TEMP .AND.  &
            &    EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, J, 9) < TEMP ) CYCLE
                       
            IF ( BANKCOLLAPSE%STATION(NUMBER_I, J) .NE. 0 ) THEN
                K=1
                EXIT LOOP2
            END IF
            
        END DO LOOP2      
        
        ! 判断是否需要继续加荷载
        IF (K==0) THEN
            EXCHANGE1%JUDGE_BANK(NUMBER_I)=0
            !WRITE(*,*) EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I), EXCHANGE1%NUMBER_LOAD(NUMBER_I), I, TEMP, EXCHANGE1%ZOOMIN(NUMBER_I)
            !PAUSE
            EXIT LOOP1
        END IF
        
    END DO LOOP1
    
    TEMP = 0.D0
    TEN_C= 0.D0
    ! 判断是否由于水流侵蚀过量引起的破坏
    IF ( EXCHANGE1%FLOW_EXCESS_JUDGE(NUMBER_I) == 1.D0 ) THEN
        
        EXCHANGE1%COLLAPSE_TIME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I))= GLOBTIME%GLOBSEC 
        
        EXCHANGE1%COLLAPSE_DEF(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I)) = 2
        
        EXCHANGE1%COLLAPSE_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I)) = 0
        
        EXCHANGE1%FLOW_EXCESS_JUDGE(NUMBER_I) = 0.D0
        
        EXCHANGE1%JUDGE_BANK(NUMBER_I) = 1
        
    ! 判断是否坍塌   
    ELSE IF (EXCHANGE1%JUDGE_BANK(NUMBER_I) == 1) THEN
        
        DO I = 1, EXCHANGE1%ELEMENT
            IF ( BANKCOLLAPSE%STATION(NUMBER_I, I) .NE. 0 ) THEN
                TEMP=TEMP+0.3333D0*(EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, I, 4) + &
            &                       EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, I, 6) + &
            &                       EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I, I, 8))
                TEN_C=TEN_C+1
            END IF
        END DO
        
        EXCHANGE1%COLLAPSE_TIME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I))= GLOBTIME%GLOBSEC 
        
        EXCHANGE1%COLLAPSE_DEF(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I)) = 1
        ! 这个是破坏面到边缘距离，转化为体积，再减去水流侵蚀的体积
        EXCHANGE1%COLLAPSE_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I)) = -TEMP/TEN_C + &
      & EXCHANGE1%ZOOMIN(NUMBER_I)*EXCHANGE1%GRID_BANK_W    
        !WRITE(*,*) TEMP, TEN_C, TEMP/TEN_C, EXCHANGE1%COLLAPSE_VOLUME(NUMBER_I, EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I))
        !pause
    END IF

    RETURN
    END SUBROUTINE FAILURE_CRITERION
#endif    
