#include 'define.h'   
#ifdef PRE_BANK_COLLAPSE
SUBROUTINE INITIAL_BANK_STRESS(NUM_CS)
    
#ifdef PRE_HYD        
    USE HYDRO
#endif

#ifdef PRE_AD
    USE Morphodynamics
#endif

#ifdef PRE_BANK_EROSION
    USE BANK_EROSION
    USE EXCHANGE
    USE DEF_EXCHANGE
    USE SED_EXCHANGE
#endif

#ifdef PRE_BANK_COLLAPSE
    USE BANK_COLLAPSE
#endif

    IMPLICIT NONE
    
    INTEGER :: I, J, K
    ! NUM OF CROSS SECTION
    INTEGER      :: NUM_CS 
    CHARACTER*40 :: FILENAME , FILENAME_PATH
    
    
    ! CALCULATE GRAVITY
    BANKCOLLAPSE%F(NUM_CS,:) = 0.D0
    DO I = 1 , EXCHANGE1%NODE
        DO J = 1 , 10
            IF (BANKCOLLAPSE%MATCH(I,J)==0) CYCLE
            BANKCOLLAPSE%F(NUM_CS,2*I)=BANKCOLLAPSE%F(NUM_CS,2*I)  &
        &  -EXCHANGE1%EXCHANGE_BANK_SIZE(NUM_CS,BANKCOLLAPSE%MATCH(I,J),10)*(SANDDENSITY_BANK-1000)*10/3.D0/1000.D0*BANKCOLLAPSE%T_LE !µ¥Î»ÎªKN
        END DO
    END DO
    
    !WRITE(FILENAME(1:4),'(I4.4)') NUM_CS
    !FILENAME(5:9)='F.RES'
    !FILENAME_PATH='MATLAB_PLOT\'//FILENAME
    !OPEN (100, FILE=FILENAME_PATH, FORM='UNFORMATTED' , STATUS='REPLACE' , ACCESS='DIRECT' , RECL=2*2)
    !DO J=1,EXCHANGE1%NODE
    !    WRITE(100, REC=J) BANKCOLLAPSE%F(NUM_CS,2*J-1), BANKCOLLAPSE%F(NUM_CS,2*J)
    !END DO
    !CLOSE(100)
    
    !FILENAME=''
    !WRITE(FILENAME(1:4),'(I4.4)') NUM_CS
    !FILENAME(5:9)='F.RES'
    !FILENAME_PATH='MATLAB_PLOT\'//FILENAME
    !OPEN (UNIT=100 , FILE=FILENAME_PATH , FORM='UNFORMATTED' , STATUS='REPLACE' , ACCESS='DIRECT' , RECL=2*2)
    !DO I = 1 , EXCHANGE1%NODE
    !    WRITE(100 , REC=I )BANKCOLLAPSE%F(NUM_CS,2*I-1),BANKCOLLAPSE%F(NUM_CS,2*I)
    !END DO
    !CLOSE(100)
    
    
    ! CALCULATE STRESS
    CALL LINEAR_ELASTIC_STIFFNESS(NUM_CS,0)






    END SUBROUTINE INITIAL_BANK_STRESS
#endif    