#include 'define.h'  
#ifdef PRE_BANK_COLLAPSE
!输出应力过程   
SUBROUTINE OUTPUT_STRESS_M(NUMBER_I)

#ifdef PRE_BANK_EROSION
        USE BANK_EROSION
        USE DEF_EXCHANGE
#endif

#ifdef PRE_BANK_COLLAPSE
        USE BANK_COLLAPSE
#endif
    
    IMPLICIT NONE
    INTEGER  , PARAMETER                       :: OT=SELECTED_REAL_KIND(8)
    REAL(OT) , ALLOCATABLE , DIMENSION(:,:)    :: EXPORT  
    INTEGER  , ALLOCATABLE , DIMENSION(:)      :: NODE_DIG 
    REAL(OT)                                   :: TEMP , X , Y , Z
    INTEGER                                    :: I , J , K , NUMBER_I  , CODE , &
                                               &  TEMP_N 
    CHARACTER*40                               :: FILENAME , FILENAME1
    
    ALLOCATE( EXPORT(EXCHANGE1%NODE,9)) !1~2位移、3~5单元应力、6~7主应力、8夹角、9为破坏信息
    
    EXPORT=0.D0
    TEMP_N=0

    DO I = 1 , EXCHANGE1%NODE
        EXPORT(I,1) = BANKCOLLAPSE%WY(NUMBER_I,2*I-1)
        EXPORT(I,2) = BANKCOLLAPSE%WY(NUMBER_I,2*I)
    END DO

    DO I = 1, EXCHANGE1%NODE
        TEMP=0.D0
        DO J = 1 , 10
            IF (BANKCOLLAPSE%MATCH(I,J)==0) CYCLE
            EXPORT(I,3)=EXPORT(I,3) + BANKCOLLAPSE%TSTRESS( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 1 )*EXCHANGE1%EXCHANGE_BANK_SIZE( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 10 )
            EXPORT(I,4)=EXPORT(I,4) + BANKCOLLAPSE%TSTRESS( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 2 )*EXCHANGE1%EXCHANGE_BANK_SIZE( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 10 )
            EXPORT(I,5)=EXPORT(I,5) + BANKCOLLAPSE%TSTRESS( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 3 )*EXCHANGE1%EXCHANGE_BANK_SIZE( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 10 )
            EXPORT(I,6)=EXPORT(I,6) + BANKCOLLAPSE%TSTRESS( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 4 )*EXCHANGE1%EXCHANGE_BANK_SIZE( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 10 )
            EXPORT(I,7)=EXPORT(I,7) + BANKCOLLAPSE%TSTRESS( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 5 )*EXCHANGE1%EXCHANGE_BANK_SIZE( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 10 )
            TEMP = TEMP + EXCHANGE1%EXCHANGE_BANK_SIZE( NUMBER_I, BANKCOLLAPSE%MATCH(I,J), 10 )
        END DO
        IF (TEMP==0.D0) CYCLE
        EXPORT(I,3) = EXPORT(I,3)/TEMP
        EXPORT(I,4) = EXPORT(I,4)/TEMP
        EXPORT(I,5) = EXPORT(I,5)/TEMP
        EXPORT(I,6) = EXPORT(I,6)/TEMP
        EXPORT(I,7) = EXPORT(I,7)/TEMP
    END DO

    DO I = 1, EXCHANGE1%NODE
        X   =0.D0
        Y   =0.D0
        Z   =0.D0
        DO J = 1 , 10
            IF ( BANKCOLLAPSE%MATCH(I,J)==0 ) CYCLE
            IF ( BANKCOLLAPSE%STATION( NUMBER_I, BANKCOLLAPSE%MATCH(I,J) )==0 ) X=X+1
            IF ( BANKCOLLAPSE%STATION( NUMBER_I, BANKCOLLAPSE%MATCH(I,J) )==1 ) Y=Y+1
            IF ( BANKCOLLAPSE%STATION( NUMBER_I, BANKCOLLAPSE%MATCH(I,J) )==2 ) Z=Z+1
        END DO
        IF (Y==0 .AND. Z==0) THEN
            EXPORT(I,9)=0
        ELSE
            IF (Y>Z)  EXPORT(I,9)=1
            IF (Y<=Z) EXPORT(I,9)=2
        END IF
    END DO

    FILENAME=''
    WRITE(FILENAME(1:3) , '(I3.3)') NUMBER_I                    !第几断面
    WRITE(FILENAME(4:6) , '(I3.3)') EXCHANGE1%NUMBER_BANKCYCLE(NUMBER_I)  !第几块岸壁
    WRITE(FILENAME(7:10) , '(I4.4)') EXCHANGE1%NUMBER_LOAD(NUMBER_I)       !第几次加载
    FILENAME(11:20)='STRESS.RES'
    FILENAME='MATLAB_PLOT\'//FILENAME
    
    OPEN(600 , FILE= FILENAME, STATUS='REPLACE', FORM='UNFORMATTED', ACCESS='DIRECT', RECL=2*9)
    K=1
    DO I = 1, EXCHANGE1%NODE
        WRITE(600 , REC= K ) (EXPORT(I,J), J=1,9)
        K=K+1
    END DO
    CLOSE(600)
    
    FILENAME(23:32)='MESHIN.RES'
    OPEN(600 , FILE= FILENAME, STATUS='REPLACE', FORM='UNFORMATTED', ACCESS='DIRECT', RECL=2*11)
    K=1
    DO I = 1 , EXCHANGE1%ELEMENT
        WRITE(600 , REC= K ) (EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,J), J=1,11)
        K=K+1
    END DO 
    CLOSE(600)
 
    !OPEN(600 , FILE= 'delet1.txt')
    !DO I = 1 , EXCHANGE1%ELEMENT
    !    WRITE(600 , '(11F8.2)' ) (EXCHANGE1%EXCHANGE_BANK_SIZE(NUMBER_I,I,J), J=1,11)
    !END DO 
    !CLOSE(600)
    
    
    IF ( ALLOCATED( EXPORT ) )  DEALLOCATE( EXPORT )


    RETURN
    END SUBROUTINE OUTPUT_STRESS_M
#endif