#include 'define.h' 
SUBROUTINE TIME_COUNTING
    
    !calculate elapsed time
    USE TIME_DIN
    USE HYDRO

    GLOBTIME%GLOBSTEP%SECSTEP=GLOBTIME%GLOBSTEP%SECSTEP+1
    
    IF (GLOBTIME%GLOBSTEP%SECSTEP>GLOBTIME%GLOBSTEP%BEFSTEP) THEN
        GLOBTIME%GLOBSEC=GLOBTIME%GLOBSEC+DT
        IF (GLOBTIME%GLOBSEC==60) THEN
            GLOBTIME%GLOBSEC=0
            GLOBTIME%GLOBMIN=GLOBTIME%GLOBMIN+1
            IF (GLOBTIME%GLOBMIN==60) THEN
                GLOBTIME%GLOBMIN=0
                GLOBTIME%GLOBHOUR=GLOBTIME%GLOBHOUR+1
                GLOBTIME%GLOBSTEP%HOURSTEP=GLOBTIME%GLOBSTEP%HOURSTEP+1
                IF (GLOBTIME%GLOBHOUR==12 .OR. &
                &   GLOBTIME%GLOBHOUR==24) GLOBTIME%GLOBHALF=GLOBTIME%GLOBHALF+1
                IF (GLOBTIME%GLOBHOUR==24) THEN
                    GLOBTIME%GLOBHOUR=0
                    GLOBTIME%GLOBDAY=GLOBTIME%GLOBDAY+1
                    GLOBTIME%GLOBSTEP%DAYSTEP=GLOBTIME%GLOBSTEP%DAYSTEP+1
                    IF (GLOBTIME%GLOBDAY==30) THEN
                        GLOBTIME%GLOBDAY=0
                        GLOBTIME%GLOBMON=GLOBTIME%GLOBMON+1
                        IF (GLOBTIME%GLOBMON==12) THEN
                            GLOBTIME%GLOBMON=0
                            GLOBTIME%GLOBYEAR=GLOBTIME%GLOBYEAR+1
                        END IF
                    END IF
                END IF
            END IF
        END IF
    END IF
    
END SUBROUTINE